[tool.poetry]
name = "02-projeto"
version = "0.1.0"
description = ""
authors = ["José Martins"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.41.1"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
